name: End-to-End Tests

on:
  workflow_dispatch:
  schedule:
    # Run weekly on Monday at 1:00 AM
    - cron: '0 1 * * 1'

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Set up Ollama
      run: |
        curl -fsSL https://ollama.com/install.sh | sh
        ollama pull llama2
        
    - name: Create test environment file
      run: |
        cat > .env << EOF
        OLLAMA_BASE_URL=http://localhost:11434
        INSTRUCT_MODEL=llama2
        REASONING_MODEL=llama2
        EMBEDDINGS_MODEL=llama2
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL=INFO
        MAX_TOKENS=2048
        TEMPERATURE=0.7
        TOP_P=0.9
        EOF
        
    - name: Run end-to-end test with sample repository
      run: |
        python main.py --github https://github.com/microsoft/vscode-extension-samples --output-dir ./test_output
        
    - name: Verify documentation output
      run: |
        if [ ! -f "./test_output/index.html" ]; then
          echo "Documentation index.html not found!"
          exit 1
        fi
        if [ ! -f "./test_output/summary.md" ]; then
          echo "Documentation summary.md not found!"
          exit 1
        fi
        if [ ! -f "./test_output/development_qa.md" ]; then
          echo "Development Q&A not found!"
          exit 1
        fi
        echo "Documentation verification successful!"
        
    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      with:
        name: documentation-output
        path: ./test_output/
        retention-days: 7
